# -*- coding: utf-8 -*-
"""WC2026_Position_Age_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiFRDHsS4UxA_iobf7P4kWE1_2jwp8CI

# Import required libraries
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

"""# Load the main dataset"""

file_path = "/content/drive/MyDrive/Dataset/standard.csv"

std = pd.read_csv(file_path, skiprows=2)

print("Original dataset shape:", std.shape)
display(std.head())

"""# Remove unnecessary rows"""

# Remove rows where player name is missing
std = std.dropna(subset=["Player"]).copy()

print("Dataset shape after removing empty player rows:", std.shape)

"""# Keep only needed columns"""

df = std[
    ["Player", "Squad", "Pos", "Age", "Min"]
].copy()

display(df.head())

"""# Clean column values"""

# Remove extra spaces
df.columns = df.columns.str.strip()

df["Pos"] = df["Pos"].astype(str).str.strip().str.upper()

"""# Convert numeric columns"""

df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
)

df["Min"] = pd.to_numeric(
    df["Min"],
    errors="coerce"
)

"""# Remove missing values"""

df = df.dropna(
    subset=["Player", "Squad", "Pos", "Age", "Min"]
)

print("Dataset shape after removing missing values:", df.shape)

"""# Filter eligible players"""

eligible = df[
    (df["Min"] >= 90) &
    (df["Pos"].isin(["DF", "MF"]))
].copy()

"""# Create readable position names"""

eligible["Position"] = eligible["Pos"].map({
    "DF": "Defender",
    "MF": "Midfielder"
})

eligible = eligible.reset_index(drop=True)

"""# Check the population"""

print("Eligible players by position:")
print(eligible["Position"].value_counts())

print("\nTotal eligible population:", len(eligible))

"""# Set the sample size"""

# Set sample size and random seed

sample_size = 120
random_seed = 42

"""# Randomly sample defenders"""

# Randomly select 120 defenders

defenders = eligible[
    eligible["Position"] == "Defender"
].sample(
    n=sample_size,
    random_state=random_seed
)

print("Defender sample size:", len(defenders))

"""# Randomly sample midfielders"""

# Randomly select 120 midfielders

midfielders = eligible[
    eligible["Position"] == "Midfielder"
].sample(
    n=sample_size,
    random_state=random_seed
)

print("Midfielder sample size:", len(midfielders))

"""# Combine both samples"""

# Combine defender and midfielder samples

sample = pd.concat(
    [defenders, midfielders],
    ignore_index=True
)

print("Sample distribution:")
print(sample["Position"].value_counts())

print("\nTotal sample size:", len(sample))

"""# Descriptive statistics"""

# Descriptive statistics for player age

summary = sample.groupby("Position")["Age"].agg(
    Count="count",
    Mean="mean",
    Standard_Deviation="std",
    Median="median",
    Minimum="min",
    Maximum="max"
).round(2)

print("Descriptive Statistics:")
display(summary)

"""# Visualisation 1: Histogram"""

# Visualisation 1: Age histogram

plt.figure(figsize=(8, 5))

plt.hist(
    defenders["Age"],
    bins=10,
    alpha=0.6,
    label="Defenders"
)

plt.hist(
    midfielders["Age"],
    bins=10,
    alpha=0.6,
    label="Midfielders"
)

plt.xlabel("Age (years)")
plt.ylabel("Number of Players")
plt.title("Age Distribution of Defenders and Midfielders")

plt.legend()

plt.tight_layout()
plt.show()

"""# Visualisation 2: Box plot"""

# Visualisation 2: Box plot

plt.figure(figsize=(7, 5))

plt.boxplot(
    [
        defenders["Age"],
        midfielders["Age"]
    ],
    tick_labels=[
        "Defenders",
        "Midfielders"
    ],
    showmeans=True
)

plt.ylabel("Age (years)")
plt.title("Age Comparison by Playing Position")

plt.tight_layout()
plt.show()

"""# Calculate 95% confidence intervals"""

def calculate_ci(data):

    mean = data.mean()

    lower, upper = stats.t.interval(
        confidence=0.95,
        df=len(data) - 1,
        loc=mean,
        scale=stats.sem(data)
    )

    return mean, lower, upper

"""# Calculate CI for both groups"""

def_mean, def_lower, def_upper = calculate_ci(
    defenders["Age"]
)

print("Defenders:")
print(f"Mean age = {def_mean:.2f}")
print(f"95% CI = [{def_lower:.2f}, {def_upper:.2f}]")

mid_mean, mid_lower, mid_upper = calculate_ci(
    midfielders["Age"]
)

print("Midfielders:")
print(f"Mean age = {mid_mean:.2f}")
print(f"95% CI = [{mid_lower:.2f}, {mid_upper:.2f}]")

"""# Visualisation 3: Mean age with 95% CI"""

# Visualisation 3: Mean age with 95% confidence intervals

positions = [
    "Defenders",
    "Midfielders"
]

means = [
    def_mean,
    mid_mean
]

errors = [
    [
        def_mean - def_lower,
        mid_mean - mid_lower
    ],
    [
        def_upper - def_mean,
        mid_upper - mid_mean
    ]
]

plt.figure(figsize=(7, 5))

plt.errorbar(
    positions,
    means,
    yerr=errors,
    fmt="o",
    markersize=9,
    capsize=8
)

plt.ylabel("Mean Age (years)")
plt.title("Mean Age with 95% Confidence Intervals")

plt.grid(
    axis="y",
    alpha=0.3
)

plt.tight_layout()
plt.show()

"""# two-sample t-test"""

# Welch two-sample t-test

defender_age = defenders["Age"].to_numpy()
midfielder_age = midfielders["Age"].to_numpy()

t_statistic, p_value = stats.ttest_ind(
    defender_age,
    midfielder_age,
    equal_var=False,
    alternative="greater"
)

print(f"t-statistic = {t_statistic:.3f}")
print(f"One-sided p-value = {p_value:.4f}")

"""# Calculate mean age difference"""

mean_difference = (
    defender_age.mean()
    -
    midfielder_age.mean()
)

print(
    f"Mean age difference = "
    f"{mean_difference:.2f} years"
)

"""# Make the statistical decision"""

alpha = 0.05

if p_value < alpha:

    print("Reject the null hypothesis.")

    print(
        "There is statistically significant evidence "
        "that defenders are older on average "
        "than midfielders."
    )

else:

    print("Fail to reject the null hypothesis.")

    print(
        "There is not enough evidence to conclude "
        "that defenders are older on average "
        "than midfielders."
    )

"""# Final results summary"""

print("\nFINAL RESULTS")
print("----------------------------")

print(f"Eligible population: {len(eligible)}")
print(f"Sample size: {len(sample)}")

print(
    f"\nDefender mean age: "
    f"{defender_age.mean():.2f} years"
)

print(
    f"Midfielder mean age: "
    f"{midfielder_age.mean():.2f} years"
)

print(
    f"Mean difference: "
    f"{mean_difference:.2f} years"
)

print(
    f"\nt-statistic: "
    f"{t_statistic:.3f}"
)

print(
    f"p-value: "
    f"{p_value:.4f}"
)

"""# Save your final analysis sample"""

output_path = (
    "/content/drive/MyDrive/Dataset/"
    "wc2026_position_age.csv"
)

sample[
    [
        "Player",
        "Squad",
        "Pos",
        "Position",
        "Age",
        "Min"
    ]
].to_csv(
    output_path,
    index=False
)

print("Dataset saved to:")
print(output_path)



